version: '3'
services:
  web:
    build: .
    container_name: fat_free_crm_web
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      RAILS_ENV: 'production'
      DATABASE_ADAPTER: 'mysql2'
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: 'changeme'
      DATABASE_HOST: db
      USERNAME: admin
      PASSWORD: changeme
      EMAIL: will@paynelabs.io

  db:
    image: mariadb:10
    container_name: fat_free_crm_db
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
